version: '3.9'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb/data:/data/db
    command: mongod --quiet --logpath /dev/null

  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    command: npm start
